server:
  port: 8093 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境
  servlet:
    multipart:
      max-file-size: 20MB       # 单个文件最大大小
      max-request-size: 100MB   # 单次请求最大大小（包含多个文件）
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
  mapper-locations: classpath*:/mapperxml/*.xml
retry:
  max-attempts: 3 # 最大重试次数
  init-interval: 1000 # 初始延迟时间，单位 ms
  multiplier: 2 # 每次重试间隔加倍（每次乘以 2）
